### ISSUE TITLE
Determination of truthiness of SemanticBuildVersion.snapshot seems counterintuitive

### ISSUE THREAD

**Issue by waynr** [vivin/gradle-semantic-build-versioning#3] opened 2016-09-01 23:43 UTC
https://github.com/vivin/gradle-semantic-build-versioning/blob/434bf29bb9683874b06faf3f1052d6488cf6253b/src/main/groovy/net/vivin/gradle/versioning/SemanticBuildVersioningPlugin.groovy#L22

This appears to be the only way that `SemanticBuilderVersion.snapshot`  can be false. 

Yet, I would expect that if I am on a "release" tag (eg 0.1.1) the plugin should infer that it is not a snapshot. I also think it would be handy to issue a warning when the `release` task is used without the `tag` task AND the current git repo is not tagged with a release version.

**Comment by vivin** [comment] 2016-09-02 00:23
The default behavior of the plugin is to assume that every version is a `SNAPSHOT` version, unless `release` has explicitly been used, or if `HEAD` is pointing to a tag and there are no changes (see [here](https://github.com/vivin/gradle-semantic-build-versioning/blob/434bf29bb9683874b06faf3f1052d6488cf6253b/src/main/java/net/vivin/gradle/versioning/VersionUtils.java#L93)). So the plugin does detect that it is at a release tag, but the problem is that it doesn't change the value of `snapshot` after - definitely something that should be fixed!

As far as displaying a warning when using `release` without `tag` when a tag for that version does not already exist, I think that is a good suggestion.

**Comment by Vampire** [comment] 2016-09-02 02:07
Why is `release` necessary anyway? `tag` is only operable if `release` is also given, so if I call `tag` I already say "Hey, I want to create a release tag" don't I?

**Comment by vivin** [comment] 2016-09-02 02:13
Fair point, but someone might want to build and install a release-version of an artifact locally, for instance, or might just want to see what the next release-version would be (via `printVersion`).

Another answer is that I implemented `tag` after I implemented `release` and so both are in there. :)

**Comment by Vampire** [comment] 2016-09-02 02:16
Ok, could be. But while I play with it, why is the uncommitted changes check on `release`? As long as I don't call `tag` it shouldn't matter, should it? I cannot do `git release printVersion` with a dirty workspace for example.

**Comment by vivin** [comment] 2016-09-02 03:10
One point I forgot to mention is that `release` is only added if there isn't another task called `release` from some other plugin. Some plugins may bring in their own `release` tasks which may actually publish an artifact. So in this instance, you don't want someone to accidentally publish uncommitted changes, as these are generally accepted to be "work in progress". 

Another issue is what happens when you make changes after checking out a tag. Let's say you checked out version 1.2.0 of the project. If the plugin didn't check for uncommitted changes when `release` is used, you could build and publish over an existing 1.2.0 version. While this is still possible to do using the plugin if you really wanted to, you have to rather explicit about it. So while this check doesn't eliminate the possibility of releasing over existing versions, it makes it difficult to do it accidentally. 

An additional reason is that sometimes people end up making multiple commits as part of some task. So in this case, it would be useful to explicitly specify that some commit is the release by using the `release` task, and assume that otherwise it is a snapshot version. For example, let's say you have a `release` task brought in by some other plugin that only publishes an artifact if the version does not end with `-SNAPSHOT`. In this case you have to make sure that you always have uncommitted changes, otherwise you could end up publishing a work in progress. A contrived example, but I hope you get the idea. I didn't want to assume what a `release` task would do; at best it may just install a local version but at worst it could actually deploy an entire site. So I decided to err on the side of caution and require that users be explicit about identifying a release version.

**Comment by Vampire** [comment] 2016-09-02 14:09
See pr #7

**Comment by vivin** [comment] 2016-09-02 21:17
Addressed in PR #7

**Closed as completed by vivin** 2016-09-02 21:17 UTC
Labels: bug
